function applyArabicSWords(text) {
  const dict = {
    'sohib': 'صاحب',
  'sabr': 'صبر',
  'sifat': 'صفت',
  'samin': 'ثمىن',
  'sadoqat': 'صداقت',
  'suhbat': 'صحبت',
  'sahifa': 'صحیفه',
  'safha': 'صفحه',
  'savob': 'ثواب',
  'sabt': 'ثبت',
  'saboq': 'سبق',
  'sanoq': 'ثناق',
  'sibgha': 'صبغه',
  'subh': 'صبح',
  'sibghatullah': 'صبغة‌الله',
  'sado': 'صدا',
  'sohibqiron': 'صاحب‌قران',
  'sadrazam': 'صدر‌اعظم',
  'sahih': 'صحیح',
  'sahro': 'صحراء',
  'suhufi': 'صحفی',
  'suhuf': 'صحف',
  'sibqat': 'صبقت',
  'salom': 'سلام',
  'silsila': 'سلسله',
  'solih': 'صالح',
  'sano': 'ثنا',
  'soniya': 'ثانیه',
  'saqofat': 'ثقافت',
  'subot': 'ثبات',
  'sadaf': 'صدف',
  'sohiblar': 'صاحبلر',
  'sifatli': 'صفتلی',
  'sodir': 'صادر',
  'sifatlar': 'صفتلر',
  'sodiq': 'صادق',
  'sadiq': 'صادق',
  'sadoqatli': 'صداقت‌لی',
  'sabrli': 'صبرلی',
  'sabrliroq': 'صبرلیراق',
  'sifatsiz': 'صفت‌سیز',
  'sohibi': 'صاحبی',
  'sifatida': 'صفتیده',
  'suhbatdosh': 'صحبت‌داش',
  'suhbatlar': 'صحبتلر',
  'samar': 'ثمر',
  'subhanallah': 'سبحان‌الله',
  'sabrtoqat': 'صبر‌تاقت',
  'sadoqatsiz': 'صداقت‌سیز',
  'sibghatli': 'صبغتلی',
   'sabringiz': 'صبرڭىز',
  'sifatlarimiz': 'صفتلرىمىز',
  'sifatlaridan': 'صفتلرىدىن',
  'sohibchilik': 'صاحبچیلیک',
  'sohibgoh': 'صاحبگأه',
  'sabrim': 'صبرىم',
  'sibghat': 'صبغت',
  'suhbatingiz': 'صحبتڭىز',
  'sohibxon': 'صاحبخان',
  'sifatlash': 'صفتلش',
  'sabrda': 'صبرده',
  'sifatxona': 'صفتخانه',
  'sohibtaqvo': 'صاحب‌تقوی',
  'sifatnom': 'صفتنامه',
  'sohibiilm': 'صاحب‌علم',
  'sibghatullah': 'صبغة‌الله',
  'sabrli emas': 'صبرلی ایمس',
  'sabrliroq': 'صبرلیراق',
  'sohiblarimiz': 'صاحبلرىمىز',
  'sabrliroqdir': 'صبرلیراق‌دیر',
  'sibghatliroq': 'صبغتلیراق',
  'sifatlashdi': 'صفتلشدی',
  'sifatlashgan': 'صفتلشگان',
  'sabrida': 'صبرىده',
  'sabring': 'صبرىڭ',
  'sifatimiz': 'صفتىمىز',
  'sohibning': 'صاحبڭڭ',
  'sifatga': 'صفتگه',
  'sifatli emas': 'صفتلی ایمس',
  'sohibiylik': 'صاحبیلیک',
  'sohibligingiz': 'صاحبلىڭىز',
  'sifatlarimizda': 'صفتلرىمىزده',
  'suhbatlarimiz': 'صحبتلرىمىز',
  'sohiblik': 'صاحبلیک',
  'sohibguzar': 'صاحبگۇذار',
  'sohibgo‘y': 'صاحبگوی',
  'sifatdosh': 'صفتداش',
  'sifatliroq': 'صفتلیراق',
  'sohibona': 'صاحبانه',
  'sadoqatimiz': 'صداقتيمىز',
  'sadoqatsizlik': 'صداقتسىزلىك',
  'sibghatini': 'صبغته‌نى',
  'sohibningiz': 'صاحبڭىز',
  'sibghatida': 'صبغته‌ده',
  'sifatlaridanmiz': 'صفتلرىدىنمىز',
  'sohibonaroq': 'صاحبانه‌راق',
  'sifatlandirmoq': 'صفتلندىرماق',
  'sifatlantirilgan': 'صفتلنتىرىلگەن'
  };

  for (let key in dict) {
    const pattern = new RegExp("\\b" + key + "\\b", "gi");
    text = text.replace(pattern, dict[key]);
  }

  return text;
}
