function applyArabicUWords(text) {
  const dict = {
    'usmon': 'عثمان',
    'umar': 'عمر',
    'umr': 'عمر',
    'ubayd': 'عبید',
    'utufat': 'عطوفت',
    'ulum': 'علوم',
    'uqda': 'عقده',
    'umum': 'عموم',
    'umumiy': 'عمومي',
    'uqubat': 'عقوبت',
    'u’yub': 'عیوب',
    'ujrat': 'عجرت',
    'uqubat': 'عقوبت',
    'utufat': 'عطوفت',
    'ubur': 'عبور',
    'umid': 'عمد',
    'uqtadir': 'اقتدار',
    'ulumo': 'علما',
    'uquq': 'حقوق',
    'ulug‘': 'عظيم',
    'ujum': 'عجم',
    'ushshoq': 'عشاق',
    'uzr': 'عذر',
    'uqlov': 'اغلاق',
    'uboh': 'اباحه',
    'umayr': 'عمیر',
    'uqba': 'عقبه',
    'ud': 'عود',
    'uqda': 'عقده',
    'u’yub': 'عیوب',
    'umum': 'عموم',
    'umumiy': 'عمومي',
    'usmon': 'عثمان',
    'umr': 'عمر',
    'umar': 'عمر',
    'ubayd': 'عبید',
    'ulbat': 'علبه',
    'ug‘ur': 'عقرب',
    'ushshaq': 'عشاق',
    'uqla': 'عقل',
    'ufoq': 'آفاق',
    'uquliy': 'عقلي',
    'ulbatin': 'علباطن',
    'uburiy': 'عبوري',
    'umron': 'عمران',
    'ulov': 'علف',
    'udum': 'عادت',
    'uluhiy': 'الوهیت',
    'uhtiyoj': 'احتیاج',
    'uhtiyot': 'احتیاط',
    'uhtiram': 'احترام',
    'uqtish': 'اقتش',
    'uqlash': 'اغلاق',
    'uqob': 'عقاب',
    'umido': 'عمده',
    'uqro': 'عقری',
    'ujratli': 'عجرتلی',
    'ulama': 'علما',
    'uzlat': 'عزله',
    'uqool': 'عقول',
    'uquloq': 'عقولاق',
    'ulmo': 'علماء',
    'uboday': 'عبادت',
    'ubudiyat': 'عبودیت',
    'uqta': 'اقتاء',
    'uqiyma': 'عقیمه',
    'udviy': 'عدوی',
    'umqiy': 'عمقی',
    'umdah': 'عمده',
    'ushshoqiy': 'عشاقی',
    'uqosha': 'عقوشه',
    'umliy': 'عملي',
    'ubayyin': 'عبیین',
    
  'usmon': 'عثمان',
  'umar': 'عمر',
  'umr': 'عمر',
  'ubayd': 'عبید',
  'utufat': 'عطوفت',
  'ulum': 'علوم',
  'uqda': 'عقده',
  'umum': 'عموم',
  'umumiy': 'عمومي',
  'uqubat': 'عقوبت',
  'u’yub': 'عیوب',
  'ujrat': 'عجرت',
  'uquq': 'حقوق',
  'ulumo': 'علما',
  'ushshoq': 'عشاق',
  'uzr': 'عذر',
  'ubur': 'عبور',
  'ujum': 'عجم',
  'ufoq': 'آفاق',
  'uhtiyoj': 'احتیاج',
  'uhtiyot': 'احتیاط',
  'uhtiram': 'احترام',
  'ud': 'عود',
  'umayr': 'عمیر',
  'uqlov': 'اغلاق',
  'uboh': 'اباحه',
  'uqba': 'عقبه',
  'uquliy': 'عقلي',
  'ulbatin': 'علباطن',
  'uburiy': 'عبوري',
  'umron': 'عمران',
  'ulov': 'علف',
  'udum': 'عادت',
  'uluhiy': 'الوهیت',
  'uqtadir': 'اقتدار',
  'uqob': 'عقاب',
  'umido': 'عمده',
  'uqro': 'عقری',
  'ujratli': 'عجرتلی',
  'ulama': 'علما',
  'uzlat': 'عزله',
  'uqool': 'عقول',
  'uquloq': 'عقولاق',
  'ulmo': 'علماء',
  'uboday': 'عبادت',
  'ubudiyat': 'عبودیت',
  'uqta': 'اقتاء',
  'uqlash': 'اغلاق',
  'uqtish': 'اقتش',
  'uhtiroz': 'احتراض',
  'uqayda': 'عقیده',
  'uquman': 'عقمان',
  'uqoyil': 'عقویل',
  'uquloqi': 'عقولاقی',
  'uqra': 'عقری',
  'uqayli': 'عقیلی',
  'ushshoqiy': 'عشاقی',
  'uqosha': 'عقوشه',
  'uqiyma': 'عقیمه',
  'uqliy': 'عقلي',
  'udviy': 'عدوی',
  'umqiy': 'عمقی',
  'umdah': 'عمده',
  'umliy': 'عملي',
  'ubayyin': 'عبیین',
  'uqiyo': 'عقیو',
  'uqiq': 'عقیق',
  'uqtima': 'اقتیما',
  'uqbar': 'عقبار',
  'uqult': 'عقولت',
  'uqon': 'عقون',
  'ulvi': 'علوی',
  'ulviy': 'علوی',
  'uloviy': 'علوفی',
  'uqim': 'عقیم',
  'uqiz': 'عقیز',
  'uqdoq': 'عقدوق',
  'ulami': 'علامی',
  'uloma': 'علما',
  'ulviyat': 'علویت',
  'uqaviy': 'عقاوی',
  'uqoniy': 'عقونی',
  'uquf': 'عقوف',
  'uqos': 'عقوص',
  'uqnam': 'عقنام',
  'udumiy': 'عدتی',
  'uqbur': 'عقبر',
  'uqlub': 'عقلب',
  'uqid': 'عقید',
  'uqzun': 'عقزون',
  'umayriy': 'عميری',
  'uqdir': 'عقدیر',
  'uqfiy': 'عقفی',
  'uddan': 'عدان',
  'uqroz': 'عقروز',
  'uqzav': 'عقزاو',
  'uqtav': 'اقتاؤ',
  'uqunam': 'عقونم',
  'uqhtim': 'عقحتیم',
  'uqhur': 'عقحور',
  'uqzu': 'عقزو',
  'uqziy': 'عقزی',
  'uqdam': 'عقدم',
  'uqulma': 'عقولما',
  'uqal': 'عقال',
  'uqulla': 'عقوللا',
  'uqir': 'عقیر',
  'uqtash': 'اقتش',
  'uqil': 'عقیل',
  'uqiyar': 'عقیار',
  'uqan': 'عقان',
  'uqida': 'عقیده',
  'uqoz': 'عقوض',
  'uqulom': 'عقولم',
  'uqayd': 'عقاید',
  'uqzim': 'عقزیم',
  'uqror': 'عقرور',
  'uqyum': 'عقیوم',
  'uqjah': 'عقجه',
  'uqfon': 'عقفون',
  'uqur': 'عقور',
  'uqsad': 'عقصاد',
  'uqumo': 'عقوما',
  'uqmah': 'عقماه',
  'uqham': 'عقهم',
  'uqnas': 'عقناس',
  'uqdur': 'عقدور',
  'uqmat': 'عقمت',
  'uqrub': 'عقروب',
  'uqlaz': 'عقلاز',
  'uqluq': 'عقلوق',
  'uqdos': 'عقدوس',
  'uqlin': 'عقلین',
  'uqdan': 'عقدان',
  'uqmiy': 'عقمی',
  'uqbos': 'عقبوس',
  'uqhar': 'عقحر',
  'uqish': 'عقیش',
  'uqviy': 'عقوی',
  'uqtar': 'عقتار',
  'uqtis': 'عقتیس',
  'uqmol': 'عقمول',
  'uqmir': 'عقمیر',
  'uqhal': 'عقحل',
  'uqbad': 'عقباد',
  'uqlil': 'عقلیل',
  'uqmoliy': 'عقمولی',
  'uqfas': 'عقفاص',
  'uqsor': 'عقصور',
  'uqbor': 'عقبور',
  'uqtur': 'عقطور',
  'uqqad': 'عققد',
  'uqtaroz': 'عقتراز',
  'uqqosa': 'عققصه',
  'uqkosh': 'عقکوش',
  'uqfur': 'عقفور',
  'uqjal': 'عقجال',
  'uqtol': 'عقتول',
  'uqfasid': 'عقفسید',
  'uqhim': 'عقحیم',
  'uqlazim': 'عقلازیم',
  'uqzura': 'عقزورا',
  'uqhimat': 'عقحیمت',
  'uqbayn': 'عقبین',
  'uqlumat': 'عقلومت',
  'uqkayf': 'عقکیف',
  'uqhasir': 'عقحصیر',
  'uqalif': 'عقالیف',
  'uqtamis': 'عقتامیس',
  'uqnash': 'عقناش',
  'uqbih': 'عقبیح',
  'uqlubi': 'عقلوبی',
  'uqnavi': 'عقنوی',
  'uqtiraz': 'عقتراز',
  'uqudam': 'عقدام',
  'uqjahon': 'عقجهان',
  'uqtiba': 'عقتیبا',
  'uqraza': 'عقرازا',
  'uqnad': 'عقناد',
  'uqruz': 'عقروز',
  'uqbaz': 'عقباز',
  'uqbash': 'عقباش',
  'uqmatin': 'عقمتین',
  'uqtal': 'عقتال',
  'uqhad': 'عقحد',
  'uqnob': 'عقنوب',
  'uqhasan': 'عقحسن',
  'uqtamin': 'عقتامین',
  'uqzibat': 'عقزبت',
  'uqlobar': 'عقلوبار',
  'uqyan': 'عقیان',
  'uqsaq': 'عقساق',
  'uqfaza': 'عقفزا',
  'uqlaya': 'عقلایا',
  'uqdamat': 'عقدامت',
  'uqday': 'عقدی',
  'uqlibas': 'عقلیباس',
  'uqdad': 'عقداد',
  'uqlal': 'عقلل',
  'uqson': 'عقصون',
  'uqmasha': 'عقمشه',
  'uqhasana': 'عقحسنه',
  'uqrob': 'عقروب',
  'uqg‘ol': 'عقغول',
  'uqboy': 'عقبوی',
  'uqmoliylik': 'عقمولیلک',
  'uqbal': 'عقبال',
  'uqfal': 'عقفال',
  'uqmil': 'عقميل',
  'uqjalil': 'عقجلیل',
  'uqazim': 'عقازیم',
  'uqbadil': 'عقبادیل',
  'uqqosir': 'عققصیر',
  'uqqadam': 'عقدم',
  'uqghina': 'عقغینا',
  'uqdayan': 'عقدایان',
  'uqmur': 'عقمور',
  'uqhash': 'عقهاش',
  'uqbah': 'عقباه',
  'uqmadin': 'عقمادین',
  'uqlimin': 'عقلیمین',
  'uqtarix': 'عقتاریخ',
  'uqg‘irat': 'عقغیرت',
  'uqnamaz': 'عقنماز',
  'uqbaraka': 'عقبرکه',
  'uqsafar': 'عقصفر',
  'uqlamat': 'عقلمت',
  'uqtarjumon': 'عقتارجمان',
  'uqdil': 'عقدیل',
  'uqnashid': 'عقنشید',
  'uqmilat': 'عقملت',
  'uqizmat': 'عقیزمت',
  'uqmanzar': 'عقمنظر',
  'uqkaf': 'عقکف',
  'uqaziyat': 'عقضیت',
  'uqdirlik': 'عقدیرلیک',
  'uqsohib': 'عقصاحب',
  'uqzar': 'عقزار',
  'uqmunazara': 'عقمنازره',
  'uqqadim': 'عقدم',
  'uqtariq': 'عقتاریق',
  'uqmanba': 'عقمنبع',
  'uqlazimlik': 'عقلازیملیک',
  'uqbalolik': 'عقبالولیک',
  'uqtiboran': 'عقتیبران',
  'uqmaslahat': 'عقمصلحت',
  'uqqasam': 'عقصم',
  'uqmastura': 'عقمستوره',
  'uqakida': 'عقعقیده',
  'uqnasihat': 'عقنصیحت',
  'uqnamlik': 'عقنملیک',
  'uqghayrat': 'عقغیرت',
  'uqmukammal': 'عقمکامل',
  'uqilmiy': 'عق علمی',
  'uqhamiyat': 'عقهمیت',
  'uqxayol': 'عقخیال',
  'uqnahiy': 'عقنحی',
  'uqmotabar': 'عق معتبر',
  'uqnimat': 'عق نعمت',
  'uqqadamiy': 'عقدمی',
  'uqhikmat': 'عق حکمت',
  'uqqaytar': 'عق قیتر',
  'uqjon': 'عق جان',
  'uqguzal': 'عق گوزل',
  'uqmillat': 'عق ملت',
  'uqnozan': 'عق نوزن',

  'uqqatiya': 'عق قطیعه',
  'uqmufid': 'عقمفید',
  'uqnahzat': 'عق نهضت',
  'uqtarbiyat': 'عق تربیت',
  'uqlavha': 'عقلوحه',
  'uqsifat': 'عق صفت',
  'uqsadr': 'عق صدر',
  'uqsharq': 'عق شرق',
  'uqgharb': 'عق غرب',
  'uqilmiylik': 'عق علمیلیک',
  'uqijtimoiy': 'عق اجتماعی',
  'uqtashabbus': 'عق تشبوس',
  'uqijtihod': 'عق اجتهاد',
  'uquzviy': 'عق عضوی',
  'uqfikr': 'عق فکر',
  'uqfikriy': 'عق فکری',
  'uqmaqsad': 'عق مقصد',
  'uqhikmatli': 'عق حکمتلی',
  'uqrasmiy': 'عق رسمی',
  'uqhayrat': 'عق حیرت',
  'uqtoqat': 'عق طاقه',
  'uqqanoat': 'عق قناعت',
  'uqtushuncha': 'عق توشونچه',
  'uqtarjimon': 'عق ترجمان',
  'uqbayon': 'عق بیان',
  'uqhayot': 'عق حیات',
  'uqjasorat': 'عق جسارت',
  'uqlaziz': 'عق عزیز',
  'uqkamol': 'عق کمال',
  'uqmarifat': 'عق معرفت',
  'uqadolat': 'عق عدالت',
  'uqittifoq': 'عق اتفاق',
  'uqrozi': 'عق راضی',
  'uqvijdon': 'عق وجدان',
  'uqlutf': 'عق لطف',
  'uqjavob': 'عق جواب',
  'uqyolg‘on': 'عق یالغان',
  'uqqasamlik': 'عق قسملیک',
  'uqrahmat': 'عق رحمت',
  'uqrahim': 'عق رحیم',
  'uqkufr': 'عق کفر',
  'uqtavhid': 'عق توحید',
  'uqlazimiy': 'عق لازمی',
  'uqsoxta': 'عق ساخت',
  'uqta’sir': 'عق تاثیر',
  'uqqurbon': 'عق قربان',
  'uqhazrat': 'عق حضرت',
  'uqnamo': 'عق نماز',
  'uqzakot': 'عق زکات',
  'uqmujtahid': 'عق مجتهد',
  'uqmaslahatli': 'عق مصلحتلی',
  'uqfatvo': 'عق فتوی',
  'uqshariat': 'عق شریعت',
  'uqdars': 'عق درس',
  'uqustoz': 'عق استاد',
  'uqmadrasah': 'عق مدرسه',
  'uqilm': 'عق علم',
  'uqimom': 'عق امام',
  'uqnamoziy': 'عق نمازی',
  'uqdo‘stlik': 'عق دوستیلیک',
  'uqqirq': 'عق قرق',
  'uqko‘mak': 'عق کومک',
  'uqtafakkur': 'عق تفکر',
  'uqma’rifat': 'عق معرفت',
  'uqko‘ngil': 'عق کنگیل',
  'uqnavbat': 'عق نوبت',
  'uqe’tiqod': 'عق اعتقاد',
  'uqqizg‘in': 'عق قیزغین',
  'uqmuomala': 'عق معامله',
  'uqrasmiyat': 'عق رسمیت',
  'uqnoz': 'عق ناز',
  'uqquvvat': 'عق قوت',
  'uqso‘z': 'عق سۆز',
  'uqtaajjub': 'عق تعجب',
  'uqmuqaddas': 'عق مقدس',
  'uqg‘alaba': 'عق غالبه',
  'uqmuxtor': 'عق مختار',
  'uqmunosabat': 'عق مناسبت',
  'uqmuomalaviy': 'عق معاملوی',
  'uqqand': 'عق قند',
  'uqodam': 'عق آدم',
  'uqtaqdir': 'عق تقدیر',
  'uqqurashuv': 'عق قراشوو',
  'uqjamoa': 'عق جمعه',
  'uqittihod': 'عق اتحاد',
  'uqlashgan': 'عق لشگان',
  'uqdo‘stona': 'عق دوستانه',
  'uqg‘amxo‘r': 'عق غمخور',
  'uqtaajjubiy': 'عق تعجبی',
  'uqqos': 'عق قوس',
  'uqmuvofiq': 'عق موافق',
  'uqmatbuot': 'عق مطبوعات',
  'uqvazifa': 'عق وظیفه',
  'uqmaqsadli': 'عق مقصدلی',
  'uqtashkiliy': 'عق تشکیلی',
  'uqrahmatli': 'عق رحمتلی',
  'uqroziy': 'عق راضی',
  'uqqoshni': 'عق قوشنی',
  'uqmo‘jiza': 'عق معجزه',
  'uqiftixor': 'عق افتخار',
  'uqlazizlik': 'عق لازیزلیک',
  'uqmadaniyat': 'عق مدنیت',
  'uqe’timod': 'عق اعتماد',
  'uqbayoniy': 'عق بیانی',
  'uqmaqola': 'عق مقاله',
  'uqmatonat': 'عق متانت',
  'uqtasdiq': 'عق تصدیق',
  'uqmaslahatlashuv': 'عق مصلحت‌لاشوو',

  'uqilmiyati': 'عق علمیات',
  'uqtazarru': 'عق تضرع',
  'uqnasihatli': 'عق نصیحتلی',
  'uqjavobgarlik': 'عق جواب‌گارلیک',
  'uqehson': 'عق احسان',
  'uqumr': 'عق عمر',
  'uqma’lumot': 'عق معلومات',
  'uqmaqsadnamo': 'عق مقصدنامه',
  'uqmuolaja': 'عق معالجه',
  'uqibodat': 'عق عبادت',
  'uqtaqdim': 'عق تقدیم',
  'uqqushish': 'عق قوشیش',
  'uqmuborak': 'عق مبارک',
  'uqqoyilmaqom': 'عق قوییل مقام',
  'uqilhom': 'عق الهم',
  'uqintihon': 'عق امتحان',
  'uqmuhabbat': 'عق محبت',
  'uqsahna': 'عق صحنه',
  'uqmanzura': 'عق منظوره',
  'uqmusibat': 'عق مصیبت',
  'uqhayotnoma': 'عق حیات‌نامه',
  'uqmaktab': 'عق مکتب',
  'uqmashhur': 'عق مشهور',
  'uqtashakkur': 'عق تشکر',
  'uqmuxtaram': 'عق محترم',
  'uqxulosa': 'عق خلاصه',
  'uqmadad': 'عق مدد',
  'uqbarakaoy': 'عق برکه‌ای',
  'uqkitob': 'عق کتاب',
  'uqmuallif': 'عق مؤلف',
  'uqqismat': 'عق قسمت',
  'uqg‘anima': 'عق غنیمت',
  'uqfiqhiy': 'عق فقهی',
  'uqijtimoiylik': 'عق اجتماعیت',
  'uqkitobiy': 'عق کتابی',
  'uqe’tiborli': 'عق اعتباری',
  'uqhaqiyqat': 'عق حقیقت',
  'uqmusofir': 'عق مسافر',
  'uqislomiy': 'عق اسلامی',
  'uqhijob': 'عق حجاب',
  'uqhalol': 'عق حلال',
  'uqtayyor': 'عق تیار',
  'uqtavsiya': 'عق توصیه',
  'uqharakat': 'عق حرکت',
  'uqfikrli': 'عق فکری‌لی',
  'uqro‘yhat': 'عق رویحت',
  'uqqonun': 'عق قانون',
  'uqhaqoniy': 'عق حقیقی',
  'uqijodkor': 'عق ایجادگر',
  'uqodati': 'عق عادت',
  'uquqiy': 'عق حقوقی',
  'uqmadaniy': 'عق مدنی',
  'uqislomiyat': 'عق اسلامیت',
  'uqruhiyat': 'عق روحیات',
  'uqma’noli': 'عق معنولی',
  'uqilhomiyat': 'عق الهمیت',
  'uqtasvir': 'عق تصویر',
  'uqzarb': 'عق ضرب',
  'uqnatija': 'عق نتیجه',
  'uqhurmatli': 'عق حرمت‌لی',
  'uqsababi': 'عق سببی',
  'uqboshqarma': 'عق بشقَرمه',
  'uqrahbariyat': 'عق رهبریت',
  'uqtayin': 'عق تعیین',
  'uqsababi': 'عق سببی',
  'uqo‘rnak': 'عق اورناک',
  'uqmuqaddima': 'عق مقدمه',
  'uqzahmat': 'عق زحمت',
  'uqqiyos': 'عق قیاس',
  'uqhikoya': 'عق حکایه',
  'uqhissa': 'عق حصه',
  'uqzavq': 'عق ذوق',
  'uqrahbar': 'عق رهبر',
  'uqmaqola': 'عق مقاله',
  'uqkitobxon': 'عق کتاب‌خوان',
  'uqilmiyona': 'عق علمیه‌نا',
  'uqmashg‘ulot': 'عق مشغولت',
  'uqduo': 'عق دعا',
  'uqta’limot': 'عق تعلیمات',
  'uqmuhim': 'عق مهم',
  'uqxursand': 'عق خورسند',
  'uqqadrli': 'عق قدر‌لی',
  'uqqimmat': 'عق قیمت',
  'uqtaalluq': 'عق تعلق',
  'uqro‘yxat': 'عق رویخت',
  'uqxulq': 'عق خلق',
  'uqmuvozanat': 'عق موازنه',
  'uqmunosib': 'عق مناسب',
  'uqqiyinchalik': 'عق قینچلیک',
  'uqbo‘lish': 'عق بولیش',
  'uqtalim': 'عق تعلیم',
  'uqyo‘lboshlovchi': 'عق یول‌بوشلَوچی',
  'uqxujjat': 'عق حجت',
  'uqo‘rinda': 'عق اورنده',
  'uqmo‘jiz': 'عق معجز',
  'uqqabari': 'عق قباره',
  'uqmusulmon': 'عق مسلمان',
  'uqkitoblar': 'عق کتب',
  'uqnomzod': 'عق نامزد',
  'uqsavob': 'عق ثواب',
  'uqnikoh': 'عق نکاح',
  'uqmuomalaviylik': 'عق معاملویلیک',
  'uqqiyinchilik': 'عق قینچیلیک',
  'uqdug‘ona': 'عق دغونه',
  'uqosh': 'عق عش',
  'uqxatolik': 'عق خطألیک',
  'uqmuvozanalik': 'عق موزانه‌لیک',
   'oqibat': 'عاقبت',
    'ojiz': 'عاجز',
    'oshiq': 'عاشق',
    'odil': 'عادل',
    'ozim': 'عازم',
    'oqil': 'عاقل',
    'ojil': 'عاجل',
    'or': 'عار',
    'obid': 'عابد',
    'obir': 'عابر',
    'odat': 'عادت',
    'oriz': 'عارض',
    'orif': 'عارف',
    'orifa': 'عارفه',
    'oshuro': 'عاشورا',
    'osim': 'عاصم',
    'otifa': 'عاطفه',
    'ofiyat': 'عافیت',
    'olam': 'عالم',
    'olim': 'عالم',
    'oliy': 'عالي',
    'om': 'عام',
    'omil': 'عامل',
    'oid': 'عاید',
    'oila': 'عایله',

  'oqibat': 'عاقبت',
  'ojiz': 'عاجز',
  'oshiq': 'عاشق',
  'odil': 'عادل',
  'ozim': 'عازم',
  'oqil': 'عاقل',
  'ojil': 'عاجل',
  'or': 'عار',
  'obid': 'عابد',
  'obir': 'عابر',
  'odat': 'عادت',
  'oriz': 'عارض',
  'orif': 'عارف',
  'orifa': 'عارفه',
  'oshuro': 'عاشورا',
  'osim': 'عاصم',
  'otifa': 'عاطفه',
  'ofiyat': 'عافیت',
  'olam': 'عالم',
  'olim': 'عالم',
  'oliy': 'عالي',
  'om': 'عام',
  'omil': 'عامل',
  'oid': 'عاید',
  'oila': 'عایله',
  'oruz': 'عروض',
  'oqibatli': 'عاقبتي',
  'oilaqi': 'عائلي',
  'oliylik': 'عاليت',
  'ozimat': 'عزیمت',
  'orib': 'عارب',
  'oshiruvchi': 'عاشرونجي',
  'ozifa': 'عاطفة',
  'ofat': 'عاهة',
  'odila': 'عادلة',
  'oboda': 'عامرة',
  'ojib': 'عجيب',
  'oqsaqol': 'عاق‌ساقل',
  'omila': 'عاملة',
  'orifaona': 'عارفة‌نا',
  'oqibatnoma': 'عاقبت‌نامه',
  'oshirin': 'عاشرین',
  'oqibatsiz': 'بلا عاقبت',
  'ojizona': 'عاجزانه',
  'oqibat': 'عاقبت',
  'oqil': 'عاقل',
  'odil': 'عادل',
  'ojil': 'عاجل',
  'ojiz': 'عاجز',
  'ozim': 'عازم',
  'osim': 'عاصم',
  'oshuro': 'عاشورا',
  'oshira': 'عاشرة',
  'oshiq': 'عاشق',
  'orif': 'عارف',
  'orifa': 'عارفه',
  'or': 'عار',
  'obid': 'عابد',
  'obir': 'عابر',
  'odat': 'عادت',
  'ofat': 'عاهة',
  'otifa': 'عاطفه',
  'ofiyat': 'عافیت',
  'oila': 'عایله',
  'olam': 'عالم',
  'olim': 'عالم',
  'oliy': 'عالي',
  'om': 'عام',
  'omil': 'عامل',
  'oid': 'عاید',
  'oruz': 'عروض',
  'oqibatli': 'عاقبتي',
  'oliylik': 'عاليت',
  'oshiruvchi': 'عاشرونجي',
  'orib': 'عارب',
  'orifaona': 'عارفة‌نا',
  'oqibatsiz': 'بلا عاقبت',
  'ozifa': 'عاطفة',
  'odila': 'عادلة',
  'oshirin': 'عاشرین',
  'oshkora': 'عاشرة',
  'oboda': 'عامرة',
  'ojib': 'عجيب',
  'oqibatiy': 'عاقبتي',
  'oqiy': 'عاقي',
  'omila': 'عاملة',
  'orifaona': 'عارفة‌نا',
  'oqibatnoma': 'عاقبت‌نامه',
  'ojizona': 'عاجزانه',
  'ozimat': 'عزیمت',
  'oshig‘i': 'عاشقه',
  'oshqovoq': 'عاشقوق',
  'olamiy': 'عالمي',
  'olimlik': 'علمیت',
  'oliyona': 'عالية',
  'oliyhimmat': 'عالي‌همة',
  'oshqozon': 'عاشق‌زن',
  'oshona': 'عاشونة',
  'oriflik': 'عرفان',
  'orifiy': 'عارفي',
  'oshkoraona': 'علنية',
  'ozimlik': 'عزميك',
  'oqillik': 'عقلية',
  'oqila': 'عاقلة',
  'oqiloq': 'عاقلوق',
  'oqillatmoq': 'تعقيل',
  'oshirilgan': 'معشور',
  'oshadigan': 'عاشقگان',
  'oshdi': 'ازدياد',
  'oshirilganlik': 'معشورية',
  'orifiynoma': 'عرفينامة',
  'oshqovoqli': 'عاشق‌قوقلي',
  'odamiy': 'آدمي',
  'oliymaqom': 'عالي‌مقام',
  'oshdimi': 'أزديادمي',
  'oqibati': 'عاقبته',
  'obidiya': 'عبادية',
  'obidlik': 'عبادليك',
  'oqibatnoma': 'عاقبتنامه',
  'oshiyona': 'عاشيانه',
  'oqillarcha': 'عاقلانة',
  'oshmagan': 'غير عاشق',
  'oqilgan': 'معقول',
  'oshiriladi': 'يعاشر',
  'odamsifat': 'آدم‌صفت',
  'oshgan': 'معشور',
  'oshli': 'عاشقلي',
  'ozimchilik': 'عازميت',
  'oshdomla': 'عاشدملا',
  'ozimoq': 'يعزم',
  'oliydaraja': 'عالي‌درجة',
  'oliyjanob': 'عالي‌جناب',
  'odamgarchilik': 'آدم‌گارچليك',
  'obodiya': 'عمارة',
  'oshilmagan': 'لم يعاشر',
  'ozimli': 'عازميلي',
  'odamlar': 'آدميان',
  'oilmuhit': 'عائلة‌محیط',
  'oshiylar': 'عاشيون',
  'oshim': 'عاشم',
  'oshchi': 'عاشچي',
  'oshov': 'عاشوف',
  








  };

  for (let key in dict) {
    const pattern = new RegExp("\\b" + key + "\\b", "gi");
    text = text.replace(pattern, dict[key]);
  }

  return text;
}
