function applyReligiousWords(text) {
  const dict = {
    'abdulloh': 'عبدالله',
    'abdurahmon': 'عبدالرحمن',
    'abdurashid': 'عبدالرشید',
    'abdulaziz': 'عبدالعزیز',
    'abdulqodir': 'عبدالقادر',
    'abdukarim': 'عبدالكریم',
    'abdujabbor': 'عبدالجبار',
    'abdunabi': 'عبدالنبی',
    'abdumalik': 'عبدالملك',
    'abdusamat': 'عبدالصمد',
    'abdulxoliq': 'عبدالخالق',
    'abdulhakim': 'عبدالحکیم',
    'abdulloh': 'عبدالله',
    'abdulfattoh': 'عبدالفتاح',
    'abdulbosit': 'عبدالباسط',
    'abdushukur': 'عبدالشکور',
    'abdulhafiz': 'عبدالحفیظ',
    'abduqodir': 'عبدالقادر',
    'abdulali': 'عبدالعلی',
    'abdulhay': 'عبدالحی',
    'ismoyil': 'اسماعیل',
    'ibratillo': 'عبرت‌الله',
    'ismatulloh': 'عصمت‌الله',
    'rahmatulloh': 'رحمت‌الله',
    'habibulloh': 'حبیب‌الله',
    'sodiqulloh': 'صادق‌الله',
    'muhammad': 'محمد',
    'muhamad': 'محمد',
    'muhammadjon': 'محمدجان',
    'muhammadali': 'محمدعلی',
    'muhamadjon': 'محمدجان',
    'muhamadali': 'محمدعلی',
    'muhammadiy': 'محمدی',
    'muhammadrizo': 'محمدرضا',
    'muhammadsodiq': 'محمدصادق',
    'muhammadtoshpoʻlat': 'محمدتاشپلات',
    'muhammadxon': 'محمدخان',
    'muhsinulloh': 'محسن‌الله',
    'saidahmad': 'سیداحمد',
    'saidaziz': 'سیدعزیز',
    'saidkarim': 'سیدکریم',
    'saidumar': 'سیدعمر',
    'saidmuhammad': 'سیدمحمد',
    'saidjamol': 'سیدجمال',
    'sadiqjon': 'صادق‌جان',
    'sobirjon': 'صابر‌جان',
    'sharifjon': 'شریف‌جان',
    'sherzodxon': 'شیرزاد‌خان',
    'rustamxon': 'رستم‌خان',
    'ulloh': 'الله',
    'xudoyor': 'خداییار',
    'xudobergan': 'خدابخشان',
    'xudoyberdi': 'خدای‌بردی',
    'xudoynazar': 'خدای‌نظر',
    'xudoyqul': 'خداقل',
    'xudoybergan': 'خدابخشان',
    'ibrohim': 'ابراهیم',
    'ahmad': 'احمد',
    'ali': 'علی',
    'umar': 'عمر',
    'usmon': 'عثمان',
    'husayn': 'حسین',
    'hasan': 'حسن',
    'fatimaxon': 'فاطمه‌خان',
    'zaynab': 'زینب',
    'maryam': 'مریم',
    'musa': 'موسی',
    'yunus': 'یونس',
    'yaqub': 'یعقوب',
    'yusuf': 'یوسف',
    'ayub': 'ایوب',
    'ishoq': 'اسحاق',
    'isroil': 'اسرائیل',
    "abduljalil": "عبدالجلیل",
"abdulhalim": "عبدالحلیم",
"abdulazim": "عبدالعظیم",
"abdullohxon": "عبدالله‌خان",
"abdurazzaq": "عبدالرزاق",
"abdulkahhor": "عبدالقاهر",
"abdulmajid": "عبدالمجید",
"abdulhak": "عبدالحق",
"abdulkarim": "عبدالکریم",
"abdusattor": "عبدالستار",
"abdushukur": "عبدالشکور",
"abdulrashid": "عبدالرشید",
"abdulbasir": "عبدالبصیر",
"abduljabbor": "عبدالجبار",
"abdugaffor": "عبدالغفور",
"abdulghani": "عبدالغنی",
"abdulkuddus": "عبدالقدوس",
"abdunazar": "عبدالنظر",
"abdulrauf": "عبدالرؤوف",
"abdulmajid": "عبدالمجید",
"abdulmuqit": "عبدالمقیت",
"abdulhamid": "عبدالحمید",
"abdulhakim": "عبدالحکیم",
"abdulhamit": "عبدالحمیت",
"abdulazim": "عبدالعظیم",
"abdulmalik": "عبدالملک",
"abdulhaq": "عبدالحق",
"abdurahim": "عبدالرحیم",
"abdulvahhob": "عبدالوهاب",
"abdulkarimxon": "عبدالکریم‌خان",
"muhammadyusuf": "محمدیوسف",
"muhammadumar": "محمدعمر",
"muhammadaliyev": "محمدعلی‌یف",
"muhammadsolih": "محمدصالح",
"muhammaddamin": "محمدامین",
"muhammadamin": "محمدامین",
"muhammadsodiq": "محمدصادق",
"muhammadxon": "محمدخان",
"muhammadkarim": "محمدکریم",
"muhammadqul": "محمدقل",
"muhammadrafiq": "محمدرفیق",
"muhammadxoji": "محمدخواجه",
"muhammadtillaxo‘ja": "محمدتلاخواجه",
"muhammadsolihxon": "محمدصالح‌خان",
"ali": "علی",
"hasan": "حسن",
"husayn": "حسین",
"umar": "عمر",
"usmon": "عثمان",
"ismatillo": "عصمت‌الله",
"rahmonqul": "رحمن‌قل",
"rahmatillo": "رحمت‌الله",
"murodullo": "مراد‌الله",
"zaynab": "زینب",
"maryam": "مریم",
"ayesha": "عایشه",
"musa": "موسی",
"yusuf": "یوسف",
"yaqub": "یعقوب",
"ibrohim": "ابراهیم",
"ishoq": "اسحاق",
"yunus": "یونس",
"ayub": "ایوب",
"shoayb": "شعیب",
"arafot": "عرفات",
"fatimaxon": "فاطمه‌خان",
"khadicha": "خدیجه",
"abbos": "عباس",
"abbosxon": "عباس‌خان",
"mahmudulloh": "محمودالله",
"sobirqul": "صابرقل",
"sodiqxon": "صادق‌خان",
"sodiqulloh": "صادق‌الله",
"habibulloh": "حبیب‌الله",
"salimxon": "سلیم‌خان",
"salohiddin": "صلاح‌الدین",
"taqi": "تقی",
"naqiy": "نقی",
"jawod": "جواد",
"ridho": "رضا",
"kazim": "کاظم",
"askariy": "عسکری",
"hadiy": "هادی",
"zaynulobidin": "زین‌العابدین",
"shohwali": "شاه‌ولی",
"sharofiddin": "شرف‌الدین",
"jaloliddin": "جلال‌الدین",
"nuriddin": "نورالدین",
"sadriddin": "صدرالدین",
"fakhriddin": "فخرالدین",
"zahiriddin": "ظهیرالدین",
"abdulmajid": "عبدالمجید",
"abdulfattah": "عبدالفتاح",
"abdulazim": "عبدالعظیم",
"abdulkarim": "عبدالکریم",
"abdulkhalil": "عبدالخلیل",
"abdulkahhor": "عبدالقهار",
"abdulmuhit": "عبدالمحيط",
"abdulalim": "عبدالعلیم",
"abdulhannan": "عبدالحنان",
"abduljalil": "عبدالجلیل",
"abdulmumin": "عبدالمؤمن",
"abdulqayyum": "عبدالقیوم",
"abdulmuqtadir": "عبدالمقتدر",
"abdulghaffor": "عبدالغفور",
"abdulghani": "عبدالغنی",
"abdulwasi": "عبدالواسع",
"abdulhalim": "عبدالحلیم",
"abdulrashid": "عبدالرشید",
"abdulrauf": "عبدالرؤوف",
"abdulhak": "عبدالحق",
"abdulhaq": "عبدالحق",
"abdulhamid": "عبدالحمید",
"abdushukur": "عبدالشکور",
"abdulazim": "عبدالعظیم",
"abdulbosit": "عبدالباسط",
"abdunur": "عبدالنور",
"abdulfattah": "عبدالفتاح",
"abdulwahid": "عبدالواحد",
"abdulkudrat": "عبدالقدرت",
"abdulhakim": "عبدالحکیم",
"abdulsamad": "عبدالصمد",
"abdujabbor": "عبدالجبار",
"abdug'ani": "عبدالغنی",
"abdulmajid": "عبدالمجید",
"abdurahim": "عبدالرحیم",
"abdurrahmon": "عبدالرحمن",
"abdurrazzoq": "عبدالرزاق",
"abdurrauf": "عبدالرؤوف",
"abduvahid": "عبدالواحد",

"shamsiddin": "شمس‌الدین",
"burhoniddin": "برهان‌الدین",
"zayniddin": "زین‌الدین",
"kamoliddin": "کمال‌الدین",
"nizomiddin": "نظام‌الدین",
"rokniddin": "رکن‌الدین",
"sharifiddin": "شریف‌الدین",
"muiniddin": "معین‌الدین",
"jaloliddin": "جلال‌الدین",
"shohiniddin": "شاهین‌الدین",
"sayfulloh": "سیف‌الله",
"sayfulloh": "سیف‌الله",
"sayidmurod": "سیدمراد",
"sayidmuhammad": "سیدمحمد",
"sayidabdulloh": "سیدعبدالله",
"sayidali": "سیدعلی",
"sayidkarim": "سیدکریم",
"sayidjamol": "سیدجمال",
"sayidazim": "سیدعظیم",

"hakimjon": "حکیم‌جان",
"rahmonjon": "رحمان‌جان",
"ismatjon": "عصمت‌جان",
"rahmatjon": "رحمت‌جان",
"muhammadjon": "محمد‌جان",
"habibjon": "حبیب‌جان",
"nasrulloh": "نصرالله",
"nasriddin": "نصرالدین",
"jamoliddin": "جمال‌الدین",
"fayziddin": "فیض‌الدین",
"nurulloh": "نورالله",
"rahimqul": "رحیم‌قل",
"karimqul": "کریم‌قل",
"rahmatqul": "رحمت‌قل",
"rahimjon": "رحیم‌جان",
"azizqul": "عزیز‌قل",
"alimqul": "علم‌قل",
"olimqul": "عالم‌قل",
"alimardon": "عالم‌مردان",
"shohmurod": "شاه‌مراد",
"shohqul": "شاه‌قل",
"shohzoda": "شاهزاده",
"malikshoh": "ملک‌شاه",
"sharipqul": "شریف‌قل",
"jalolqul": "جلال‌قل",
"abdulbari": "عبدالباری",
"abdunabi": "عبدالنبی",
"abdunnasir": "عبدالناصر",
"abdulhalim": "عبدالحلیم",
"abdulhadi": "عبدالهادی",
"abduljalol": "عبدالجلال",
"abdulg'ani": "عبدالغنی",
"abdulmajeed": "عبدالمجید",
"abdulalim": "عبدالعلیم",
"abdulwadood": "عبدالودود",
"abdulazim": "عبدالعظیم",
"abdulmajid": "عبدالمجید",
"abdulkhaliq": "عبدالخالق",
"abdulmaqsud": "عبدالمقصود",
"abdulmutallib": "عبدالمطلب",
"abdulhannan": "عبدالحنان",
"abdulg'ayur": "عبدالغیور",
"abdulmuqtadir": "عبدالمقتدر",
"abdulrashid": "عبدالرشید",
"abdulkudrat": "عبدالقدرت",
"abdulmuizz": "عبدالمعز",
"abdulwahhab": "عبدالوهاب",
"abduljawad": "عبدالجواد",
"abdulkarim": "عبدالکریم",
"abdulmalik": "عبدالملک",

"muhammadsodiq": "محمدصادق",
"muhammadtursun": "محمدترسون",
"muhammadusmon": "محمدعثمان",
"muhammadyunus": "محمدیونس",
"muhammadamin": "محمدامین",
"muhammadali": "محمدعلی",
"muhammadsalim": "محمدسلیم",
"muhammadkarim": "محمدکریم",
"muhammadrizo": "محمدرضا",
"muhammadhasan": "محمدحسن",
"muhammadahmad": "محمداحمد",
"muhammadsaid": "محمدسعید",
"muhammadyusuf": "محمدیوسف",
"muhammadaziz": "محمدعزیز",
"muhammadhusayn": "محمدحسین",
"muhammadsharif": "محمدشریف",
"muhammadabbos": "محمدعباس",
"muhammadfayz": "محمدفیض",
"muhammadjalol": "محمدجلال",
"muhammaddamin": "محمدامین",

"sayyidali": "سیدعلی",
"sayyidmuhammad": "سیدمحمد",
"sayyidkarim": "سیدکریم",
"sayyidaziz": "سیدعزیز",
"sayyidhasan": "سیدحسن",
"sayyidahmad": "سیداحمد",
"sayyidjamol": "سیدجمال",
"sayyidrahmon": "سیدرحمن",
"sayyidqul": "سید‌قل",
"sayyidxudoyor": "سیدخداییار",

"hafizulloh": "حافظ‌الله",
"mujtaba": "مجتبی",
"muiniddin": "معین‌الدین",
"mustafa": "مصطفی",
"sharofiddin": "شرف‌الدین",
"fayziddin": "فیض‌الدین",
"jamoliddin": "جمال‌الدین",
"rahimulloh": "رحیم‌الله",
"ahmadulloh": "احمد‌الله",
"rahmatqul": "رحمت‌قل",
"rahimqul": "رحیم‌قل",
"jalolqul": "جلال‌قل",
"azizqul": "عزیز‌قل",
"alimqul": "علم‌قل",
"olimqul": "عالم‌قل",
"muslimqul": "مسلم‌قل",

"abbosbek": "عباس‌بیک",
"hasanbek": "حسن‌بیک",
"husaynqul": "حسین‌قل",
"rahmatbek": "رحمت‌بیک",
"aliqul": "علی‌قل",
"ahmadbek": "احمد‌بیک",
"abduvahid": "عبدالواحد",
"abduraxim": "عبدالرحیم",
"abduvali": "عبدالولی",
"abdurashid": "عبدالرشید",
"abdufattah": "عبدالفتاح",
"abdullohxon": "عبدالله‌خان",
"muhammadxon": "محمد‌خان",
"sayidxon": "سید‌خان",
"alimardon": "علم‌مردان",
"habibulloh": "حبیب‌الله",
"shamsulloh": "شمس‌الله",
"nurulloh": "نور‌الله",
"zafarulloh": "ظفر‌الله",
"jamolulloh": "جمال‌الله",
"rasululloh": "رسول‌الله",
"ilhomulloh": "الهام‌الله",
"tohirqul": "طاهر‌قل",
"sobirqul": "صابر‌قل",
"salohiddin": "صلاح‌الدین",
"fakhriddin": "فخر‌الدین",
"sadriddin": "صدر‌الدین",
"zahiriddin": "ظهیر‌الدین",
"burhoniddin": "برهان‌الدین",
"nizomiddin": "نظام‌الدین",
"kamoliddin": "کمال‌الدین",
"mujibulloh": "مجیب‌الله",
"karimulloh": "کریم‌الله",
"nozimulloh": "ناظم‌الله",
"olimulloh": "عالم‌الله",
"alijon": "علی‌جان",
"ahmadjon": "احمد‌جان",
"rahmatjon": "رحمت‌جان",
"ismatulloh": "عصمت‌الله",
"zahirulloh": "ظاهر‌الله",
"javohirulloh": "جواهر‌الله",
"naimulloh": "نعیم‌الله",
"sobirulloh": "صابر‌الله",
"sharifulloh": "شریف‌الله",
"tohirulloh": "طاهر‌الله",
"fayzulloh": "فیض‌الله",
"rahmonulloh": "رحمن‌الله",
"hakimulloh": "حکیم‌الله",
"zohidulloh": "زاهد‌الله",
"sharofulloh": "شرف‌الله",
"nuriddin": "نورالدین",
"muzaffariddin": "مظفرالدین",
"zaynulobidin": "زین‌العابدین",
"badriddin": "بدرالدین",
"jaloliddin": "جلال‌الدین",
"sayyidmardon": "سیدمردان",
"sayyidkarim": "سیدکریم",
"sayyidnazr": "سیدنظر",
"sayyidamir": "سیدامیر",
"sayyidxon": "سید‌خان",
"sayyidjon": "سید‌جان",
"sayyidhasan": "سیدحسن",
"sayyidqosim": "سیدقاسم",
"sayyidismat": "سیدعصمت",
"sayyidismatulloh": "سیدعصمت‌الله",
"sayyidmuxtor": "سیدمختار",
"sayyidsharif": "سیدشریف",
"sayyidmaxdum": "سیدمخدوم",
"qodirqul": "قادر‌قل",
"qodirxon": "قادر‌خان",
"qodirjon": "قادر‌جان",
"qodirulloh": "قادر‌الله",
"xonqul": "خان‌قل",
"xonqulov": "خان‌قل‌اف",
"xonjon": "خان‌جان",
"xonkarim": "خان‌کریم",
"karimjon": "کریم‌جان",
"karimxon": "کریم‌خان",
"karimxoji": "کریم‌خواجه",
"karimbek": "کریم‌بیک",
"azizbek": "عزیز‌بیک",
"azizqul": "عزیز‌قل",
"azizulloh": "عزیز‌الله",
"aziziddin": "عزیزالدین",
"xojiakbar": "خواجه‌اکبر",
"xojiislom": "خواجه‌اسلام",
"xojiakrom": "خواجه‌اکرم",
"xojiabror": "خواجه‌ابرار",
"xojiabdulaziz": "خواجه‌عبدالعزیز",
"xojiabduvahid": "خواجه‌عبدالواحد",
"xojiismat": "خواجه‌عصمت",
"xojiismatulloh": "خواجه‌عصمت‌الله",
"xojiusmon": "خواجه‌عثمان",
"xojiibrohim": "خواجه‌ابراهیم",
"xojiabdulloh": "خواجه‌عبدالله",
"xojiqul": "خواجه‌قل",
"xojiqulov": "خواجه‌قل‌اف",
"abdug'affor": "عبدالغفور",
"abduzohid": "عبدالزاهد",
"abdubosit": "عبدالباسط",
"abdumanon": "عبدالمنان",
"abduvahhob": "عبدالوهاب",
"abdutavakkul": "عبدالتوکل",
"abdujalil": "عبدالجلیل",
"abdujalol": "عبدالجلال",
"abdumatin": "عبدالمتین",
"abdura'uf": "عبدالرؤوف",
"abdushakoor": "عبدالشکور",
"abdushukur": "عبدالشکور",
"abdulhakimxon": "عبدالحکیم‌خان",
"abdulhalimxon": "عبدالحلیم‌خان",
"abdulhayy": "عبدالحی",
"abdulmuqtadir": "عبدالمقتدر",
"abdulkarimxoja": "عبدالکریم‌خواجه",
"abdulazizbek": "عبدالعزیز‌بیک",
"abdulqodirxon": "عبدالقادر‌خان",
"abdulghafforqul": "عبدالغفور‌قل",

"nurxon": "نور‌خان",
"nurqul": "نور‌قل",
"nuriddinbek": "نورالدین‌بیک",
"nuriddinxon": "نورالدین‌خان",
"fayzullo": "فیض‌الله",
"fayziddin": "فیض‌الدین",
"fayzkarim": "فیض‌کریم",
"fayzqul": "فیض‌قل",
"fayzbek": "فیض‌بیک",
"fayzrizo": "فیض‌رضا",
"tohirqul": "طاهر‌قل",
"tohirjon": "طاهر‌جان",
"tohirbek": "طاهر‌بیک",
"tohirmurod": "طاهر‌مراد",
"zohidxon": "زاهد‌خان",
"zohidbek": "زاهد‌بیک",
"zohidqul": "زاهد‌قل",
"hakimqul": "حکیم‌قل",
"hakimjon": "حکیم‌جان",
"hakimxon": "حکیم‌خان",
"sharifqul": "شریف‌قل",
"sharifbek": "شریف‌بیک",
"sharifxoja": "شریف‌خواجه",

"shamsiddin": "شمس‌الدین",
"shamsulloh": "شمس‌الله",
"shamsqul": "شمس‌قل",
"shamsxoja": "شمس‌خواجه",
"shamsbek": "شمس‌بیک",
"shamsurrahmon": "شمس‌الرحمن",
"shamsuniso": "شمس‌النساء",
"shamsiy": "شمسی",
"shamsiddinxon": "شمس‌الدین‌خان",
"shamsiddinbek": "شمس‌الدین‌بیک",

"xojaahmad": "خواجه‌احمد",
"xojaismat": "خواجه‌عصمت",
"xojamuhammad": "خواجه‌محمد",
"xojaali": "خواجه‌علی",
"xojausmon": "خواجه‌عثمان",
"xojaibrohim": "خواجه‌ابراهیم",
"xojaaziz": "خواجه‌عزیز",
"xojaabdulloh": "خواجه‌عبدالله",
"xojamurod": "خواجه‌مراد",
"xojaakrom": "خواجه‌اکرم",
"xojaabror": "خواجه‌ابرار",
"xojaqul": "خواجه‌قل",
"xojaismatulloh": "خواجه‌عصمت‌الله",
"xojaaziziddin": "خواجه‌عزیزالدین",
"xojaaliqul": "خواجه‌علی‌قل",
"xojaqodir": "خواجه‌قادر",
"xojaqudrat": "خواجه‌قدرت",

"mavlaviy": "مولوی",
"mavlono": "مولانا",
"mavlonoabdulloh": "مولانا عبدالله",
"mavlonojalol": "مولانا جلال",
"mavlonoakbar": "مولانا اکبر",
"mavlonoabdulkarim": "مولانا عبدالکریم",
"mavlonokarimjon": "مولانا کریم‌جان",
"mavlonosharif": "مولانا شریف",
"mavlonoqosim": "مولانا قاسم",
"mavlonoismat": "مولانا عصمت",
"mavlonoaziz": "مولانا عزیز",
"jalolqul": "جلال‌قل",
"jalolbek": "جلال‌بیک",
"jaloliddinbek": "جلال‌الدین‌بیک",
"jaloliddinxon": "جلال‌الدین‌خان",
"jalolxoja": "جلال‌خواجه",
"jaloljon": "جلال‌جان",
"jalolsharif": "جلال‌شریف",

"zokirqul": "ذاکر‌قل",
"zokirjon": "ذاکر‌جان",
"zokirbek": "ذاکر‌بیک",
"zokirulloh": "ذاکر‌الله",
"zokiriddin": "ذاکرالدین",

"muzaffarqul": "مظفر‌قل",
"muzaffariddin": "مظفرالدین",
"muzaffarbek": "مظفر‌بیک",
"muzaffarkarim": "مظفر‌کریم",
"muzaffarmuhammad": "مظفر‌محمد",

"rahmatqul": "رحمت‌قل",
"rahmatbek": "رحمت‌بیک",
"rahmatillo": "رحمت‌الله",
"rahmatulloh": "رحمت‌الله",
"rahmatkarim": "رحمت‌کریم",
"rahmatismat": "رحمت‌عصمت",
"rahmatmurod": "رحمت‌مراد",

"sharofqul": "شرف‌قل",
"sharofulloh": "شرف‌الله",
"sharofiddin": "شرف‌الدین",
"sharofbek": "شرف‌بیک",
"sharofxon": "شرف‌خان",
"sharofjon": "شرف‌جان",

"mahmudqul": "محمود‌قل",
"mahmudbek": "محمود‌بیک",
"mahmudulloh": "محمود‌الله",
"mahmudiddin": "محمودالدین",

"g'afurqul": "غفور‌قل",
"g'afurbek": "غفور‌بیک",
"g'afurxon": "غفور‌خان",
"g'afurjon": "غفور‌جان",
"g'afurulloh": "غفور‌الله",

"halilqul": "خلیل‌قل",
"halilulloh": "خلیل‌الله",
"haliljon": "خلیل‌جان",
"haliliddin": "خلیل‌الدین",

"latifqul": "لطیف‌قل",
"latifjon": "لطیف‌جان",
"latifulloh": "لطیف‌الله",
"latifbek": "لطیف‌بیک",
"latifiddin": "لطیف‌الدین",

"hasanqul": "حسن‌قل",
"hasanulloh": "حسن‌الله",
"hasaniddin": "حسن‌الدین",
"hasanbek": "حسن‌بیک",
"hasanxon": "حسن‌خان",

"husaynqul": "حسین‌قل",
"husaynulloh": "حسین‌الله",
"husayniddin": "حسین‌الدین",
"husaynjon": "حسین‌جان",
"husaynsharif": "حسین‌شریف",

"ismatullo": "عصمت‌الله",
"ismatillo": "عصمت‌الله",
"ismatbek": "عصمت‌بیک",
"ismatqul": "عصمت‌قل",
"ismatxon": "عصمت‌خان",

"karimqul": "کریم‌قل",
"karimulloh": "کریم‌الله",
"karimiddin": "کریم‌الدین",
"karimbek": "کریم‌بیک",
"karimxon": "کریم‌خان",

"solihqul": "صالح‌قل",
"solihbek": "صالح‌بیک",
"solihulloh": "صالح‌الله",
"solihiddin": "صالح‌الدین",
"solihmurod": "صالح‌مراد",

"sodiqqul": "صادق‌قل",
"sodiqbek": "صادق‌بیک",
"sodiqjon": "صادق‌جان",
"sodiqxon": "صادق‌خان",
"sodiqulloh": "صادق‌الله",
"sodiqiddin": "صادق‌الدین",
"naimulloh": "نعیم‌الله",
"naimqul": "نعیم‌قل",
"naimiddin": "نعیم‌الدین",
"naimbek": "نعیم‌بیک",
"naimjon": "نعیم‌جان",

"maqbulqul": "مقبول‌قل",
"maqbuljon": "مقبول‌جان",
"maqbulbek": "مقبول‌بیک",
"maqbuliddin": "مقبول‌الدین",
"maqbululloh": "مقبول‌الله",

"mubinulloh": "مبین‌الله",
"mubiniddin": "مبین‌الدین",
"mubinqul": "مبین‌قل",
"mubinbek": "مبین‌بیک",

"bashirqul": "بشیر‌قل",
"bashirbek": "بشیر‌بیک",
"bashiriddin": "بشیر‌الدین",
"bashirulloh": "بشیر‌الله",

"zuhurqul": "ظهور‌قل",
"zuhurulloh": "ظهور‌الله",
"zuhuriddin": "ظهور‌الدین",
"zuhurbek": "ظهور‌بیک",

"shamsqul": "شمس‌قل",
"shamsjon": "شمس‌جان",
"shamsiddinbek": "شمس‌الدین‌بیک",
"shamsullah": "شمس‌الله",

"arifjon": "عارف‌جان",
"arifbek": "عارف‌بیک",
"arifqul": "عارف‌قل",
"arifiddin": "عارف‌الدین",
"arifulloh": "عارف‌الله",

"azimjon": "عظیم‌جان",
"azimqul": "عظیم‌قل",
"azimulloh": "عظیم‌الله",
"azimiddin": "عظیم‌الدین",
"azimbek": "عظیم‌بیک",

"jalilqul": "جلیل‌قل",
"jalilulloh": "جلیل‌الله",
"jaliliddin": "جلیل‌الدین",
"jalilbek": "جلیل‌بیک",

"aminjon": "امین‌جان",
"aminqul": "امین‌قل",
"aminbek": "امین‌بیک",
"aminiddin": "امین‌الدین",
"aminulloh": "امین‌الله",

"saidalikhon": "سیدعلی‌خان",
"saidzohid": "سیدزاهد",
"saidrahmon": "سیدرحمن",
"saidqosim": "سیدقاسم",
"saidzokir": "سیدذاکر",
"saidhakim": "سیدحکیم",

"murodqul": "مراد‌قل",
"murodbek": "مراد‌بیک",
"murodiddin": "مراد‌الدین",
"murodulloh": "مراد‌الله",
"murodjon": "مراد‌جان",

"majidqul": "مجید‌قل",
"majidbek": "مجید‌بیک",
"majididdin": "مجید‌الدین",
"majidulloh": "مجید‌الله",

"rahmonqul": "رحمن‌قل",
"rahmonbek": "رحمن‌بیک",
"rahmoniddin": "رحمن‌الدین",
"rahmonulloh": "رحمن‌الله",
"rahmonjon": "رحمن‌جان",

"sirojiddin": "سراج‌الدین",
"siroqul": "سراج‌قل",
"sirojon": "سراج‌جان",
"sirojulloh": "سراج‌الله",

"sharipqul": "شریف‌قل",
"sharipulloh": "شریف‌الله",
"sharipiddin": "شریف‌الدین",
"sharipbek": "شریف‌بیک",
"sharipxon": "شریف‌خان",

"taqiulloh": "تقی‌الله",
"taqiiddin": "تقی‌الدین",
"taqiqul": "تقی‌قل",
"taqibek": "تقی‌بیک",

"ridhoqul": "رضا‌قل",
"ridhoiddin": "رضا‌الدین",
"ridhojon": "رضا‌جان",
"ridhoulloh": "رضا‌الله",

"kazimqul": "کاظم‌قل",
"kazimjon": "کاظم‌جان",
"kazimulloh": "کاظم‌الله",
"kazimiddin": "کاظم‌الدین",

"jawodqul": "جواد‌قل",
"jawodulloh": "جواد‌الله",
"jawodbek": "جواد‌بیک",
"jawodiddin": "جواد‌الدین",

"askariqul": "عسکری‌قل",
"askarijon": "عسکری‌جان",
"askariulloh": "عسکری‌الله",
"askariiddin": "عسکری‌الدین",
"fatimaxon": "فاطمه‌خان",
"zaynabxon": "زینب‌خان",
"maryamjon": "مریم‌جان",
"ayesha": "عایشه",
"khadicha": "خدیجه",
"ummuhanifa": "ام‌حنیفه",
"ummusalma": "ام‌سلمه",
"ummukulsum": "ام‌کلثوم",
"ummuzaynab": "ام‌زینب",
"ummurayhana": "ام‌ریحانه",

"bibifatima": "بی‌بی فاطمه",
"bibizaynab": "بی‌بی زینب",
"bibikhadija": "بی‌بی خدیجه",
"bibimahbuba": "بی‌بی محبوبه",
"bibinazira": "بی‌بی نظیره",
"bibiayesha": "بی‌بی عایشه",
"bibinazokat": "بی‌بی نزاکت",
"bibijon": "بی‌بی‌جان",
"bibigul": "بی‌بی‌گل",

"gulbibi": "گل‌بی‌بی",
"gulzaynab": "گل‌زینب",
"gulayesha": "گل‌عایشه",
"gulfatima": "گل‌فاطمه",
"gulmuharram": "گل‌محرم",
"guljon": "گل‌جان",
"gulbahor": "گل‌بهار",
"gulmurod": "گل‌مراد",
"gulfayz": "گل‌فیض",
"gulfayzabonu": "گل‌فیض‌بانو",

"mahnaz": "ماه‌ناز",
"mahbuba": "محبوبة",
"mahsuma": "محصومة",
"mahzuna": "محزونة",
"mahnoor": "ماه‌نور",
"mahjabeen": "محجبه",
"mahro": "ماه‌رو",
"mahsura": "محصوره",
"mahya": "محیا",
"mahrukh": "ماه‌رخ",
"mahsura": "محصوره",

"asiye": "آسیه",
"salma": "سلمه",
"tayyiba": "طیبه",
"safiya": "صفیه",
"rukhiya": "رقیه",
"marziya": "مرضیه",
"rabiya": "رابعه",
"najiba": "نجیبه",
"nazira": "نظیره",
"zohra": "زهرا",
"shamsiyya": "شمسیه",
"qudsiyya": "قدسیه",
"noorjahan": "نورجهان",
"noorzoda": "نورزاده",
"noorulhuda": "نورالهدی",
"noorulloh": "نورالله",

"aybibi": "عیب‌بی‌بی",
"bibiismat": "بی‌بی عصمت",
"bibiulkarim": "بی‌بی الکریم",
"bibiniso": "بی‌بی‌نساء",
"bibihawa": "بی‌بی هوا",
"bibiqamar": "بی‌بی قمر",
"bibijahon": "بی‌بی جهان",
"bibiqudsiya": "بی‌بی قدسیه",
"bibilatofa": "بی‌بی لطیفه",

"sultana": "سلطانه",
"shahzoda": "شاهزاده",
"malika": "ملیکه",
"malikaoy": "ملیکه آی",
"malikagul": "ملیکه‌گل",
"shahgul": "شاه‌گل",
"shahbibi": "شاه‌بی‌بی",
"shahrbano": "شهربانو",
"shahrnoz": "شهرناز",
"shahdokht": "شاه‌دخت",
"shahjahon": "شاه‌جهان",
"gulshah": "گل‌شاه",
"shahafroza": "شاه‌افروزه",
"jalolkarim": "جلال‌کریم",
"jalolnur": "جلال‌نور",
"jalolmurod": "جلال‌مراد",
"jalolrahmon": "جلال‌رحمن",
"jalolfayz": "جلال‌فیض",
"jaloliddinxoja": "جلال‌الدین‌خواجه",

"abboskarim": "عباس‌کریم",
"abbosxon": "عباس‌خان",
"abbosbek": "عباس‌بیک",
"abbosqul": "عباس‌قل",
"abbosiddin": "عباس‌الدین",
"abbosxoja": "عباس‌خواجه",

"sabirqul": "صابر‌قل",
"sabirbek": "صابر‌بیک",
"sabiriddin": "صابر‌الدین",
"sabirjon": "صابر‌جان",
"sabirulloh": "صابر‌الله",

"sodiquddin": "صادق‌الدین",
"sodiqkarim": "صادق‌کریم",
"sodiqabbos": "صادق‌عباس",
"sodiqrahmon": "صادق‌رحمن",
"sodiqfayz": "صادق‌فیض",

"aziznur": "عزیز‌نور",
"aziziddin": "عزیز‌الدین",
"azizmurod": "عزیز‌مراد",
"azizrahmon": "عزیز‌رحمن",
"azizquljon": "عزیز‌قل‌جان",
"azizsharif": "عزیز‌شریف",

"mubinkarim": "مبین‌کریم",
"mubinrahmon": "مبین‌رحمن",
"mubinsharif": "مبین‌شریف",
"mubinabbos": "مبین‌عباس",
"mubinxoja": "مبین‌خواجه",

"hakimnur": "حکیم‌نور",
"hakimqul": "حکیم‌قل",
"hakimiddin": "حکیم‌الدین",
"hakimmurod": "حکیم‌مراد",
"hakimrahmon": "حکیم‌رحمن",

"sharifnur": "شریف‌نور",
"sharifmurod": "شریف‌مراد",
"shariffayz": "شریف‌فیض",
"sharifrahmon": "شریف‌رحمن",
"sharifkarim": "شریف‌کریم",

"rahmonxoja": "رحمن‌خواجه",
"rahmoniddin": "رحمن‌الدین",
"rahmonzoda": "رحمن‌زاده",
"rahmonjon": "رحمن‌جان",
"rahmonbek": "رحمن‌بیک",

"fayzxoja": "فیض‌خواجه",
"fayzbek": "فیض‌بیک",
"fayziddin": "فیض‌الدین",
"fayzrahmon": "فیض‌رحمن",
"fayzkarim": "فیض‌کریم",

"mustafaqul": "مصطفی‌قل",
"mustafabek": "مصطفی‌بیک",
"mustafaiddin": "مصطفی‌الدین",
"mustafaxoja": "مصطفی‌خواجه",
"mustafakarim": "مصطفی‌کریم",

"ahmadnur": "احمد‌نور",
"ahmadkarim": "احمد‌کریم",
"ahmadrahmon": "احمد‌رحمن",
"ahmadqul": "احمد‌قل",
"ahmadiddin": "احمد‌الدین",

"abdunur": "عبدالنور",
"abdurazzaq": "عبدالرزاق",
"abdurrauf": "عبدالرؤوف",
"abdulmuqtadir": "عبدالمقتدر",
"abdulmajid": "عبدالمجید",
"abduljawad": "عبدالجواد",
"abdulhakim": "عبدالحکیم",
"abdulkuddus": "عبدالقدوس",
"abdulmuhit": "عبدالمحیط",

"noorqul": "نور‌قل",
"nooriddin": "نور‌الدین",
"noorbek": "نور‌بیک",
"noorjon": "نور‌جان",
"noorullah": "نور‌الله",

"rahimkarim": "رحیم‌کریم",
"rahimnur": "رحیم‌نور",
"rahimjon": "رحیم‌جان",
"rahimulloh": "رحیم‌الله",

"abbosrahmon": "عباس‌رحمن",
"abbosnur": "عباس‌نور",
"abboskarim": "عباس‌کریم",

"karimkarim": "کریم‌کریم",
"karimsharif": "کریم‌شریف",
"karimrahmon": "کریم‌رحمن",
"karimxoja": "کریم‌خواجه",

"sharofxoja": "شرف‌خواجه",
"sharofqul": "شرف‌قل",
"sharofjon": "شرف‌جان",
"sharofbek": "شرف‌بیک",
"sharofiddin": "شرف‌الدین",

"xojaqosim": "خواجه‌قاسم",
"xojaabbos": "خواجه‌عباس",
"xojaali": "خواجه‌علی",
"xojaumar": "خواجه‌عمر",
"xojaabbosqul": "خواجه‌عباس‌قل",
"xojaaziziddin": "خواجه‌عزیزالدین",

"nurmuhammad": "نورمحمد",
"nuriddinmurod": "نورالدین‌مراد",
"nurkarim": "نورکریم",
"nurrahmon": "نوررحمن",
"nursharif": "نورشریف",

"azizulloh": "عزیز‌الله",
"aziziddinxon": "عزیزالدین‌خان",
"azizsharifxoja": "عزیز‌شریف‌خواجه",

"saidulkarim": "سیدالکریم",
"sayidaziz": "سیدعزیز",
"sayidmubin": "سیدمبین",
"sayidnur": "سیدنور",
"sayididdin": "سیدالدین",
"sayidmuhammad": "سیدمحمد",

"hakimiddinbek": "حکیم‌الدین‌بیک",
"hakimmubin": "حکیم‌مبین",
"hakimfayz": "حکیم‌فیض",
"hakimnuriddin": "حکیم‌نورالدین"










  };

  for (let key in dict) {
    const pattern = new RegExp("\\b" + key + "\\b", "gi");
    text = text.replace(pattern, dict[key]);
  }

  return text;
}
